server:
  port: ${SERVER_PORT}
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        max-age: 31536000
      timeout: P365D
#  ssl:
#    key-store: ${KEY_STORE_PATH}
#    key-store-password: ${KEY_STORE_PASSWORD}
#    key-alias: ${KEY_STORE_AS}

spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#
#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
#    username: sa

#  postgresql
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

admin:
  verify_code: ${ADMIN_VERIFY_CODE}

naver:
  client_id: ${NAVER_CLIENT_ID}
  secret: ${NAVER_CLIENT_SECRET}

upload:
  image:
    dir: ${UPLOAD_IMAGE_DIR}
    path: ${UPLOAD_IMAGE_PATH}

baseurl: ${BASE_URL}

storage:
  url: ${STORAGE_URL}

resource:
  image:
    path: ${RESOURCE_IMAGE_PATH}